### ISSUE TITLE
widget::ghq::source() には FZF_DEFAULT_OPTS='--ansi' にする必要があるようです

### ISSUE THREAD

**Issue by soya-miyoshi** [NagayamaRyoga/dotfiles#1]
@NagayamaRyoga さん
[ブログ](https://www.m3tech.blog/entry/dotfiles-bonsai) の記事を参考にして自分も色々と取り入れてみました。
素敵なdotfilesありがとうございます！

[セッションをリポジトリごとに分ける](https://www.m3tech.blog/entry/dotfiles-bonsai#:~:text=tmux/tmux.conf%22-,%5B%E3%81%93%E3%81%A0%E3%82%8F%E3%82%8A%5D%20%E3%82%BB%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%94%E3%81%A8%E3%81%AB%E5%88%86%E3%81%91%E3%82%8B,-%E7%AD%86%E8%80%85%E3%81%AF%E3%82%B7%E3%82%A7%E3%83%AB) 
機能を導入して気づいたのですが、
この機能で使われている
`widget::ghq::source()` の
https://github.com/NagayamaRyoga/dotfiles/blob/8ad78d6a35586d441432988ce743273adb2fb0b9/config/zsh/.zshrc#L98
の部分
```
    local session color icon green="\e[32m" blue="\e[34m" reset="\e[m" checked="\uf631" unchecked="\uf630"
    (省略) 
            printf "$color$icon %s$reset\n" "$repo"
```

の $color の部分は、あらかじめ`FZF_DEFAULT_OPTS='--ansi' ` としておかないと、色のコード自体が文字列として認識されてしまい、
fzfでのリポジトリの選択がうまくいかなくなるようです。
Nagayamaさんのdotfiles では結構離れた箇所でそのOPTSを設定していると思います。

記事にもその旨を追記していただいたほうが、分かりやすいかと思いましたので、コメントさせていただきました。

よろしければご確認のほどお願いします。

**Comment by NagayamaRyoga** [comment]
@soya-miyoshi ご指摘ありがとうございます。

他の箇所でカラーコードに言及している箇所がないことと、コードスニペットとしての可搬性を上げるために、記事内で掲載している `widget::ghq::select` 内の `fzf` コマンドに直接 `--ansi` オプションを追加いたしました。
ご確認くださいませ。

**Comment by soya-miyoshi** [comment]
良いと思います！
